print("Welcome to the tip calculator.")
total_bill = float(input("What was the total bill? $"))
tip_percentage = float(input("What percentage tip would you like to give? 10, 12, or 15? "))
total_bill_with_tip = total_bill * (1 + (tip_percentage / 100))
no_of_people = int(input("How many people to split the bill? "))
person_share = round((total_bill_with_tip / no_of_people),2)
print(f"Each person should pay : ${person_share}")